### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by Theletha** [aaaboypop/N4A-V2#1]
It's spewing out a lot of [duplicate errors](https://i.imgur.com/A5axWAC.png): 
```Log file created at: 2019/08/27 18:30:32
Running on machine: TW
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0827 18:30:32.719889 28360 relu_layer.cu:26] Check failed: error == cudaSuccess (10 vs. 0)  invalid device ordinal
```

I was using the CUDA tab with these settings: [CUDA](https://i.imgur.com/zt7uhTn.png)
I'm not sure if its user error or an actual bug? i used same image frames in Vulkan and that seems to work.
I'm using a Nvidia 1080Ti with my integrated intel graphics also enabled.

**Comment by aaaboypop** [comment]
did you try using gpu-z to check if your gpu working properly?
or try reinstall nvidia driver
